main:
  push:
    - services:
        - docker
      stages:
        # -----------------------------------------------------------
        # 1. 构建并推送 Backend 基础镜像
        # -----------------------------------------------------------
        - name: Backend Docker build & push
          script:
            - docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/backend:latest -f docker/backend/Dockerfile .
            - docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/backend:latest

        # -----------------------------------------------------------
        # 2. 构建并推送 Frontend 基础镜像
        # -----------------------------------------------------------
        - name: Frontend Docker build & push
          script:
            - docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/frontend:latest -f docker/frontend/Dockerfile .
            - docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/frontend:latest

        # -----------------------------------------------------------
        # 3. 动态生成统一镜像 Dockerfile 并构建
        # -----------------------------------------------------------
        - name: Unified Docker build & push
          script:
            # 动态生成 Dockerfile.unified (Linux Shell 语法)
            # 使用刚才推送的镜像作为 FROM 源
            - |
              cat <<EOF > Dockerfile.unified
              FROM ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/frontend:latest AS frontend
              FROM ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/backend:latest

              # 安装 Nginx 和 Supervisor
              RUN apt-get update && apt-get install -y --no-install-recommends nginx supervisor && \\
                  mkdir -p /var/www/html /var/log/nginx /var/cache/nginx /var/lib/nginx && \\
                  chown -R www-data:www-data /var/www/html /var/log/nginx /var/cache/nginx /var/lib/nginx && \\
                  rm -rf /var/lib/apt/lists/*

              # 从前端镜像复制文件
              COPY --from=frontend /usr/share/nginx/html /var/www/html
              COPY --from=frontend /etc/nginx/nginx.conf /etc/nginx/nginx.conf

              # 修复 Nginx 配置 (包含关键的正则修复)
              RUN sed -i "s|^user .*|user www-data;|g" /etc/nginx/nginx.conf && \\
                  sed -i "s|/usr/share/nginx/html|/var/www/html|g" /etc/nginx/nginx.conf && \\
                  sed -i "s|proxy_pass .*backend_upstream;|proxy_pass http://127.0.0.1:8000;|g" /etc/nginx/nginx.conf && \\
                  sed -i "s|proxy_pass .*backend_upstream/static/|proxy_pass http://127.0.0.1:8000/static/|g" /etc/nginx/nginx.conf && \\
                  sed -i "/resolver/d" /etc/nginx/nginx.conf && \\
                  sed -i "/set .*backend_upstream/d" /etc/nginx/nginx.conf

              # 创建 Supervisor 配置目录
              RUN mkdir -p /etc/supervisor/conf.d /var/log/supervisor /var/log/nginx

              # 写入 Supervisor 配置文件
              RUN echo '[supervisord]' > /etc/supervisor/conf.d/yolo.conf && \\
                  echo 'nodaemon=true' >> /etc/supervisor/conf.d/yolo.conf && \\
                  echo 'logfile=/var/log/supervisor/supervisord.log' >> /etc/supervisor/conf.d/yolo.conf && \\
                  echo 'pidfile=/var/run/supervisord.pid' >> /etc/supervisor/conf.d/yolo.conf && \\
                  echo '' >> /etc/supervisor/conf.d/yolo.conf && \\
                  echo '[program:backend]' >> /etc/supervisor/conf.d/yolo.conf && \\
                  echo 'command=python -m uvicorn src.main:app --host 0.0.0.0 --port 8000' >> /etc/supervisor/conf.d/yolo.conf && \\
                  echo 'directory=/app' >> /etc/supervisor/conf.d/yolo.conf && \\
                  echo 'autostart=true' >> /etc/supervisor/conf.d/yolo.conf && \\
                  echo 'autorestart=true' >> /etc/supervisor/conf.d/yolo.conf && \\
                  echo 'stdout_logfile=/dev/stdout' >> /etc/supervisor/conf.d/yolo.conf && \\
                  echo 'stdout_logfile_maxbytes=0' >> /etc/supervisor/conf.d/yolo.conf && \\
                  echo 'stderr_logfile=/dev/stderr' >> /etc/supervisor/conf.d/yolo.conf && \\
                  echo 'stderr_logfile_maxbytes=0' >> /etc/supervisor/conf.d/yolo.conf && \\
                  echo '' >> /etc/supervisor/conf.d/yolo.conf && \\
                  echo '[program:frontend]' >> /etc/supervisor/conf.d/yolo.conf && \\
                  echo 'command=nginx -g "daemon off;"' >> /etc/supervisor/conf.d/yolo.conf && \\
                  echo 'autostart=true' >> /etc/supervisor/conf.d/yolo.conf && \\
                  echo 'autorestart=true' >> /etc/supervisor/conf.d/yolo.conf && \\
                  echo 'stdout_logfile=/dev/stdout' >> /etc/supervisor/conf.d/yolo.conf && \\
                  echo 'stdout_logfile_maxbytes=0' >> /etc/supervisor/conf.d/yolo.conf && \\
                  echo 'stderr_logfile=/dev/stderr' >> /etc/supervisor/conf.d/yolo.conf && \\
                  echo 'stderr_logfile_maxbytes=0' >> /etc/supervisor/conf.d/yolo.conf

              EXPOSE 8000 80
              CMD ["supervisord", "-c", "/etc/supervisor/conf.d/yolo.conf"]
              EOF

            # 打印生成的 Dockerfile 用于调试（可选）
            - cat Dockerfile.unified

            # 构建并推送最终统一镜像
            - docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/yolo:latest -f Dockerfile.unified .
            - docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/yolo:latest