main:
  push:
    - services:
        - docker
      stages:
        - name: Build unified yolo image
          script: |
            # 构建 backend 镜像（作为中间镜像）
            docker build -t yolo-backend:temp -f docker/backend/Dockerfile .
            
            # 构建 frontend 镜像（作为中间镜像）
            docker build -t yolo-frontend:temp -f docker/frontend/Dockerfile .
            
            # 创建合并镜像的 Dockerfile（临时）
            cat > /tmp/Dockerfile.unified << 'EOF'
            FROM yolo-backend:temp AS backend
            FROM yolo-frontend:temp AS frontend
            
            # 最终镜像基于 nginx（前端基础镜像更轻量）
            FROM nginx:alpine
            
            # 从 backend 阶段复制 Python 环境和代码
            COPY --from=backend /usr/local /usr/local
            COPY --from=backend /app /app/backend
            COPY --from=backend /etc/apt /etc/apt
            
            # 从 frontend 阶段复制前端文件
            COPY --from=frontend /usr/share/nginx/html /usr/share/nginx/html
            COPY --from=frontend /etc/nginx/nginx.conf /etc/nginx/nginx.conf
            
            # 安装启动脚本依赖和进程管理工具
            RUN apk add --no-cache bash curl supervisor
            
            # 创建 supervisord 配置文件
            RUN mkdir -p /etc/supervisor/conf.d
            COPY << 'SUPERVISOR' /etc/supervisor/conf.d/yolo.conf
            [supervisord]
            nodaemon=true
            logfile=/var/log/supervisor/supervisord.log
            pidfile=/var/run/supervisord.pid
            
            [program:backend]
            command=/usr/local/bin/python -m uvicorn src.main:app --host 0.0.0.0 --port 8000
            directory=/app/backend
            autostart=true
            autorestart=true
            stdout_logfile=/dev/stdout
            stdout_logfile_maxbytes=0
            stderr_logfile=/dev/stderr
            stderr_logfile_maxbytes=0
            
            [program:frontend]
            command=/usr/sbin/nginx -g "daemon off;"
            autostart=true
            autorestart=true
            stdout_logfile=/dev/stdout
            stdout_logfile_maxbytes=0
            stderr_logfile=/dev/stderr
            stderr_logfile_maxbytes=0
            SUPERVISOR
            
            EXPOSE 8000 80
            
            CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/yolo.conf"]
            EOF
            
            # 构建最终镜像
            docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest -f /tmp/Dockerfile.unified .
        
        # 推送合并镜像
        - name: Push unified yolo image
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest